name: Build and publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - Samples/**
        README.md
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      PACKAGE_PATH: ./packages

    steps:
      - name: Get source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Set build version
        uses: dotnet/nbgv@master
      - name: Install dependencies
        run: dotnet restore
      - name: Build and test
        run: dotnet test --configuration Release --no-restore
      - name: Pack
        run: dotnet pack --configuration Release --no-build --output ${{env.PACKAGE_PATH}}
      - name: Push to NuGet Gallery
        run: dotnet nuget push ${{env.PACKAGE_PATH}}/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
        if: github.event_name == 'push'
